version: '3.1'
services:
  db:
    image: mysql
    container_name: pontosdeinteresse
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - pontodeinteresse_data:/var/lib/mysql

volumes:
  pontodeinteresse_data: